version: 2

sources:
  - name: landing_delta
    database: lh_weather
    schema: dbo
#    loaded_at_field: m_updated_at_dttm
    tables:
    - name: city
      identifier: city
    - name: ld_weather_astro
      identifier: ld_weather_astro
    - name: ld_weather_astro_forecast
      identifier: ld_weather_astro_forecast
    - name: ld_weather_forecast
      identifier: ld_weather_forecast
    - name: ld_weather_measure
      identifier: ld_weather_measure

  - name: seed
    database: wh_weather
    schema: dbt
    tables:
    - name: city
      identifier: city

  - name: int
    database: wh_weather
    schema: dbt_int
    tables:
    - name: country_codes
      identifier: country_codes