CREATE TABLE [dbt_silver].[s_fct_weather_forecast] (

	[m_valid_dt] date NULL, 
	[weather_pk] varchar(256) NULL, 
	[forecast_dt] date NULL, 
	[city_nm] varchar(30) NULL, 
	[city_fk] varchar(256) NULL, 
	[country_cd] varchar(2) NULL, 
	[country_nm] varchar(30) NULL, 
	[county_nm] varchar(50) NULL, 
	[cloud_coverage_pct] int NULL, 
	[cloud_coverage_cd] varchar(19) NOT NULL, 
	[gust_kph_no] decimal(14,4) NULL, 
	[gust_miph_no] numeric(21,10) NULL, 
	[heatindex_c_no] decimal(14,4) NULL, 
	[heatindex_f_no] decimal(19,6) NULL, 
	[heatindex_k_no] numeric(15,4) NULL, 
	[humidity_pct] int NULL, 
	[humidity_cd] varchar(9) NOT NULL, 
	[is_day_flg] bit NULL, 
	[precip_mm_no] decimal(14,4) NULL, 
	[precip_mm_cd] varchar(15) NOT NULL, 
	[pressure_mb_no] decimal(14,4) NULL, 
	[temp_c_no] decimal(14,4) NULL, 
	[temp_c_cd] varchar(9) NOT NULL, 
	[temp_f_no] decimal(19,6) NULL, 
	[temp_f_cd] varchar(9) NOT NULL, 
	[temp_k_no] numeric(15,4) NULL, 
	[temp_k_cd] varchar(9) NOT NULL, 
	[temp_feelslike_no] decimal(14,4) NULL, 
	[date_dtt] datetime2(6) NULL, 
	[time_epoch] int NULL, 
	[rain_chance_pct] int NULL, 
	[rain_chance_cd] varchar(9) NOT NULL, 
	[snow_chance_pct] int NULL, 
	[snow_chance_cd] varchar(9) NOT NULL, 
	[uv_no] decimal(14,4) NULL, 
	[vis_km_no] decimal(14,4) NULL, 
	[vis_mi_no] numeric(21,10) NULL, 
	[wind_dir_cd] varchar(8) NULL, 
	[wind_kph_no] decimal(14,4) NULL, 
	[wind_kph_cd] varchar(15) NOT NULL, 
	[wind_miph_no] numeric(21,10) NULL, 
	[wind_miph_cd] varchar(15) NOT NULL, 
	[windchill_c_no] decimal(14,4) NULL, 
	[windchill_f_no] decimal(19,6) NULL, 
	[windchill_k_no] numeric(15,4) NULL, 
	[m_extracted_at_dttm] datetime2(6) NULL, 
	[m_updated_at_dttm] datetime2(6) NULL
);